version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.3
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
  post_build:
      commands:
        - aws s3 cp _site s3://my-jekyll-site-bucket/resume/ --recursive
