version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7.8
    commands:
      - gem install bundler
      - bundle install
  build:
    commands:
      - bundle exec jekyll build -d build_output
artifacts:
  files:
    - '**/*'
  base-directory: 'build_output'
